name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build package
      working-directory: ./mail
      run: go build -v ./...

    - name: Build CLI
      working-directory: ./cmd
      run: go build -v ./...

    - name: Test package
      working-directory: ./mail
      run: go test -v ./...
  
    - name: Test CLI
      working-directory: ./cmd
      run: go test -v ./...
